version = 1

[[annotations]]
path = [
  ".envrc",
  ".github/workflows/**",
  ".gitignore",
  "flake.lock",
  "flake.nix",
  "foundry.toml",
  "remappings.txt",
  "slither.config.json",
  "soldeer.lock",
  "REUSE.toml",
  "README.md",
  "PLAN.md",
  "audit/mutation-test-scans.json",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
